package Model;
// Generated Nov 30, 2017 6:43:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Card generated by hbm2java
 */
@Entity
@Table(name="Card"
    ,schema="dbo"
    ,catalog="scissorrockpaper"
)
public class Card  implements java.io.Serializable {


     private long id;
     private Serializable cardName;
     private Set<Deposit> deposits = new HashSet<Deposit>(0);

    public Card() {
    }

	
    public Card(long id, Serializable cardName) {
        this.id = id;
        this.cardName = cardName;
    }
    public Card(long id, Serializable cardName, Set<Deposit> deposits) {
       this.id = id;
       this.cardName = cardName;
       this.deposits = deposits;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="CardName", nullable=false)
    public Serializable getCardName() {
        return this.cardName;
    }
    
    public void setCardName(Serializable cardName) {
        this.cardName = cardName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="card")
    public Set<Deposit> getDeposits() {
        return this.deposits;
    }
    
    public void setDeposits(Set<Deposit> deposits) {
        this.deposits = deposits;
    }




}


