package Model;
// Generated Dec 16, 2017 6:08:38 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Card generated by hbm2java
 */
@Entity
@Table(name="Card"
    ,schema="dbo"
    ,catalog="SRP"
)
public class Card  implements java.io.Serializable {


     private long id;
     private String cardName;
     private Set<Deposit> deposits = new HashSet<Deposit>(0);

    public Card() {
    }

	
    public Card(long id, String cardName) {
        this.id = id;
        this.cardName = cardName;
    }
    public Card(long id, String cardName, Set<Deposit> deposits) {
       this.id = id;
       this.cardName = cardName;
       this.deposits = deposits;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="CardName", nullable=false)
    public String getCardName() {
        return this.cardName;
    }
    
    public void setCardName(String cardName) {
        this.cardName = cardName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="card")
    public Set<Deposit> getDeposits() {
        return this.deposits;
    }
    
    public void setDeposits(Set<Deposit> deposits) {
        this.deposits = deposits;
    }




}


