package Model;
// Generated Dec 16, 2017 6:08:38 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Deposit generated by hbm2java
 */
@Entity
@Table(name="Deposit"
    ,schema="dbo"
    ,catalog="SRP"
)
public class Deposit  implements java.io.Serializable {


     private long id;
     private Card card;
     private Player player;
     private String serial;
     private Date createTime;

    public Deposit() {
    }

    public Deposit(long id, Card card, Player player, String serial, Date createTime) {
       this.id = id;
       this.card = card;
       this.player = player;
       this.serial = serial;
       this.createTime = createTime;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCard", nullable=false)
    public Card getCard() {
        return this.card;
    }
    
    public void setCard(Card card) {
        this.card = card;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdPlayer", nullable=false)
    public Player getPlayer() {
        return this.player;
    }
    
    public void setPlayer(Player player) {
        this.player = player;
    }

    
    @Column(name="Serial", nullable=false)
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Create_time", nullable=false, length=10)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


