package Model;
// Generated Nov 30, 2017 6:43:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Deposit generated by hbm2java
 */
@Entity
@Table(name="Deposit"
    ,schema="dbo"
    ,catalog="scissorrockpaper"
)
public class Deposit  implements java.io.Serializable {


     private long id;
     private Card card;
     private User user;
     private Serializable serial;

    public Deposit() {
    }

    public Deposit(long id, Card card, User user, Serializable serial) {
       this.id = id;
       this.card = card;
       this.user = user;
       this.serial = serial;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCard", nullable=false)
    public Card getCard() {
        return this.card;
    }
    
    public void setCard(Card card) {
        this.card = card;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdUser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="Serial", nullable=false)
    public Serializable getSerial() {
        return this.serial;
    }
    
    public void setSerial(Serializable serial) {
        this.serial = serial;
    }




}


