package Model;
// Generated Dec 16, 2017 6:08:38 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Player generated by hbm2java
 */
@Entity
@Table(name="Player"
    ,schema="dbo"
    ,catalog="SRP"
)
public class Player  implements java.io.Serializable {


    @Id
    @Column(name="Id", unique=true, nullable=false)
    @GeneratedValue
     private long id;
    @Column(name="playerName", nullable=false)
     private String playerName;
@Column(name="password", nullable=false)
     private String password;
@Column(name="email", nullable=false)
     private String email;
@Column(name="amount", nullable=false)
     private long amount;
@OneToMany(fetch=FetchType.LAZY, mappedBy="player")
     private Set<Deposit> deposits = new HashSet<Deposit>(0);

    public Player() {
    }

	
     public Player(String playerName, String password, String email, long amount) {
      
//         this.id = -1;
        this.playerName = playerName;
        this.password = password;
        this.email = email;
        this.amount = amount;
    }
    public Player(long id, String playerName, String password, String email, long amount) {
        this.id = id;
        this.playerName = playerName;
        this.password = password;
        this.email = email;
        this.amount = amount;
    }
    public Player(long id, String playerName, String password, String email, long amount, Set<Deposit> deposits) {
       this.id = id;
       this.playerName = playerName;
       this.password = password;
       this.email = email;
       this.amount = amount;
       this.deposits = deposits;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    public String getPlayerName() {
        return this.playerName;
    }
    
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    public long getAmount() {
        return this.amount;
    }
    
    public void setAmount(long amount) {
        this.amount = amount;
    }

    public Set<Deposit> getDeposits() {
        return this.deposits;
    }
    
    public void setDeposits(Set<Deposit> deposits) {
        this.deposits = deposits;
    }




}


