/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChatSample;

//import Hibernate.HibernateUtil;

import DAO.PlayerDAO;
import Model.Player;
import javax.swing.JOptionPane;

//import Hibernate.Model.User;

/**
 *
 * @author HK
 */
public class fRegister extends javax.swing.JFrame {

    /**
     * Creates new form fLogin
     */
    public fRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tUserName = new javax.swing.JTextField();
        tEmail = new javax.swing.JTextField();
        bRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tPass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bRegister1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(tUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 22, 250, 60));
        jPanel1.add(tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 250, 52));

        bRegister.setText("Register");
        bRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterAction(evt);
            }
        });
        jPanel1.add(bRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 250, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Email");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 113, 52));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UserName");
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 113, 52));
        jPanel1.add(tPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 93, 250, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password");
        jLabel3.setFocusable(false);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, 113, 52));

        bRegister1.setText("Cancel");
        bRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegister1RegisterAction(evt);
            }
        });
        jPanel1.add(bRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 390, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterAction
        
        PlayerDAO model = new PlayerDAO();
        String userName = tUserName.getText();
        String password = tPass.getText();
        String email = tEmail.getText();
        boolean rs = false;
        if(userName.isEmpty() && password.isEmpty() && email.isEmpty())
            JOptionPane.showMessageDialog( null,"Cần nhập đầy đủ thông tin!");
        else if (model.uniquePlayername(userName)!=null)
            JOptionPane.showMessageDialog( null,"Tên đăng nhập đã tồn tại!");
        else{
            rs = model.AddPlayer(new Player( userName
                , password
                , email, 100));
            JOptionPane.showMessageDialog( null,"Đăng ký thành công!");
            this.dispose();
        }
        
        
//        (new fClient(Integer.parseInt(tEmail.getText().trim()),tUserName.getText().trim(),9999,100)).setVisible(true);
//        this.setVisible(false);
        
    }//GEN-LAST:event_RegisterAction

    private void bRegister1RegisterAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegister1RegisterAction
        this.dispose();
    }//GEN-LAST:event_bRegister1RegisterAction

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(fLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(fLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(fLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(fLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new fRegister().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRegister;
    private javax.swing.JButton bRegister1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tPass;
    private javax.swing.JTextField tUserName;
    // End of variables declaration//GEN-END:variables
}
