/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChatSample;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Dictionary;
import java.util.HashMap;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HK
 */
public class fServer extends javax.swing.JFrame {

    /**
     * Creates new form fServer
     */
    Server server;
    public fServer() {
        initComponents();
        server = new Server(9999);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tServer = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Server_Start(evt);
            }
        });

        jButton2.setText("End");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Server_End(evt);
            }
        });

        tServer.setColumns(20);
        tServer.setRows(5);
        jScrollPane1.setViewportView(tServer);
        tServer.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Server_Start(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Server_Start
      Thread thread = new Thread(server);
      thread.start();
       
        
        
        
        
    }//GEN-LAST:event_Server_Start

    private void Server_End(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Server_End
        
        server.EndServer();
    }//GEN-LAST:event_Server_End

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fServer().setVisible(true);
            }
        });
    }

    
    
    
    public class ClientHandler implements Runnable{
    ObjectInputStream reader; 
    ObjectOutputStream writer;
    public boolean isActive = true;
    public int id = 0;
    

    public ClientHandler(Socket socket,ObjectOutputStream out,ObjectInputStream in){
      this.writer = out;
      this.reader = in;
    }
   
    @Override
    public void run() {
           
        try {
                while( true){

                    System.out.println("server is watting");
                    ClientObject client =(ClientObject)reader.readObject();
                    if(client.message.isEmpty() ){
                        if(!ServerHandler.Contain(client.id, client.isReady)){
                            id = client.id;
                            ServerHandler.users.add(client);
                        }
                            //update new users
//                            writer.reset();
                             for(ObjectOutputStream write : ServerHandler.GetOOS()){
                                write.writeObject(ServerHandler.users.toArray(new ClientObject[4]));
                                write.reset();
                             }
                            continue;
                        }
                      
                    
                    for(ObjectOutputStream write : ServerHandler.GetOOS()){
                        write.writeObject(new ClientObject(client.id ,client.message, client.name, client.isReady));
                    }

                    tServer.append(client.message + "\n");

                }
        } catch (IOException ex) {
             System.out.println("Can't create thread for client " + ex.getMessage());
             //remove from users ???????
             //????
             ServerHandler.RemoveUser(id);
             for(ObjectOutputStream write : ServerHandler.GetOOS()){
                 try {
                     write.writeObject(ServerHandler.users.toArray(new ClientObject[4]));
                     write.reset();
                 } catch (IOException ex1) {
                     System.out.println("client disconnected " + ex.getMessage());
                 }
                
                
             }
              ServerHandler.Remove(writer);
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(fServer.class.getName()).log(Level.SEVERE, null, ex);
        }

        
              
                  
              
         
        
    }
    
}
    
    public class Server implements Runnable{
    private int port;
    private boolean isRunning = true;
    private ServerSocket server;
    private ThreadPoolExecutor execute;
            
            
    public Server(int port){
        this.port = port;
    }
    private void StartServer(){
        try {
            isRunning = true;
            server = new ServerSocket(port);
            execute = new ThreadPoolExecutor(4,4,0L,
                    TimeUnit.MILLISECONDS,
                    new LinkedBlockingQueue<Runnable>());       
            while(true){
                System.out.println("Server's starting");
                // create thread for handle new client connect to server
                Socket sock = server.accept();
                if(CountActive() > 2 ){
                    System.out.println("phong da day");
                    sock.getOutputStream().write(1);
//                    JOptionPane.showMessageDialog(null, "phong da day");
                }
                else{
                    sock.getOutputStream().write(0);
                    ObjectOutputStream out = new ObjectOutputStream(sock.getOutputStream());
                    ServerHandler.Add(out);
                    ObjectInputStream in = new ObjectInputStream(sock.getInputStream());
                    ClientHandler handler = new ClientHandler(sock,out,in);
                    
                    execute.execute(handler);
                    
                }
                
            }
            
        } catch (IOException ex) {
            System.out.println("Server can't start " + ex.getMessage());
        }
    }
    public void EndServer(){
        if(isRunning)
        try {
            server.close();
        } catch (IOException ex) {
            System.out.println("Server can't stop " + ex.getMessage());
        }
    }
 
     public int CountActive(){
        return execute.getActiveCount();
    }
    
    @Override
    public void run() {
       StartServer();
    }
}
    public static class ServerHandler{
     private static ArrayList<ObjectOutputStream> oos = new ArrayList<>();
     public static ArrayList<ClientObject> users = new ArrayList<>();
     public static ArrayList<ObjectOutputStream> GetOOS(){
         return oos;
         
     }
     public static void Remove(ObjectOutputStream os){
         oos.remove(os);
     }
      public static void Add(ObjectOutputStream os){
         oos.add(os);
     }
      public static boolean Contain(int id,boolean isReady){
          for(int i = 0 ; i < users.size() ; i++){
              if(users.get(i).id == id){
                  ClientObject user = users.get(i);
                  user.isReady = isReady;
                  users.set(i, user);
                  return true;
              }
          }
           return false;
      }
       public static void RemoveUser(int id){
          for(int i = 0 ; i < users.size() ; i++){
              if(users.get(i).id == id){
                 users.remove(i);
              }
     }
    }  
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tServer;
    // End of variables declaration//GEN-END:variables
}
